#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "forgejo-runner"
name = "Forgejo Runner"
description.en = "Runner for Forgejo"
description.fr = "Runner pour Forgejo"

version = "12.6.3~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://forgejo.org"
demo = "https://code.forgejo.org"
admindoc = "https://forgejo.org/docs/latest/admin/runner-installation/"
userdoc = "https://forgejo.org/docs/latest/user/actions/#forgejo-runner"
code = "https://code.forgejo.org/forgejo/runner"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "615M"
ram.build = "250M"
ram.runtime = "50M"

[install]
    [install.token]
    ask.en = "This token can be retrieved at this location: https://forgejo.domain.tld/admin/actions/runners"
    ask.fr = "Ce token peut être récupéré à cet emplacement : https://forgejo.domain.tld/admin/actions/runners"
    type = "string"

    [install.forgejo_url]
    ask.en = "Please enter Forgejo instance URL"
    ask.fr = "Veuillez entrer l'URL de votre instance Forgejo"
    type = "string"
    example = "https://forge.domain.tld"

    [install.runner_name]
    ask.en = "The runner's name visible on the forge"
    ask.fr = "Le nom de l'exécuteur visible sur la forge"
    type = "string"
    example = "runner"

[resources]

    [resources.sources]

        [resources.sources.main]
        amd64.url = "https://code.forgejo.org/forgejo/runner/releases/download/v12.6.3/forgejo-runner-12.6.3-linux-amd64"
        amd64.sha256 = "469920d9df6884f1d9d7da129e231b13ff8c5b81c794d51c8d5e0965d47b0a57"
        arm64.url = "https://code.forgejo.org/forgejo/runner/releases/download/v12.6.3/forgejo-runner-12.6.3-linux-arm64"
        arm64.sha256 = "2575a484de366d0f39f0234b671e6c9ecd7310caa0c3d226137ce7edf96026e6"
        in_subdir = false
        extract = false
        rename = "forgejo-runner"

        autoupdate.strategy = "latest_forgejo_release"
        autoupdate.asset.amd64 = "^forgejo-runner-.*-linux-amd64$"
        autoupdate.asset.arm64 = "^forgejo-runner-.*-linux-arm64$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]

    [resources.apt]
    packages = "ca-certificates, git, git-lfs, curl, tar"

    extras.docker.repo = "https://download.docker.com/linux/debian bullseye stable"
    extras.docker.key = "https://download.docker.com/linux/debian/gpg"
    extras.docker.packages = "docker-ce, docker-ce-cli, containerd.io"
